### ISSUE TITLE
Can not reuse LNURL address.

### ISSUE THREAD

**Issue by 20a8vnf30** [lnbits/lnurlp#13]
I had a user with a LNURLp address, no problems there.
- Deleted the user without first deleting the LNURLp address.
- Created a new user.
- Tried creating a LNURLp with the same address (name@lnbits.mydomain.com) and got the error:

Username already exists. Try a different one.
500

The referenced user no long exists, but it seems his LNURLp address is not deleted.
If I first delete the LNURLp address and THEN delete the user, I can reuse the address.

LNbits 0.10.8

**Comment by motorina0** [comment]
How was the user deleted?

**Comment by 20a8vnf30** [comment]
> How was the user deleted?

This was a long time ago but I believe I deleted the user using the GUI of the User Manager extenstion.
Either that or I logged in AS the user and deleted the wallet from the user's GUI.
