### ISSUE TITLE
Potential issue with local LNURLp extension

### ISSUE THREAD

**Issue by n-e-t-d-i-v-e-r** [lnbits/lnurlp#17]
Hi there, not sure if it’s an issue or only a bad configuration of my local LNbits environment.

But if I install the extension LNURLp on any local server (raspibolt) and cofigure and generate an invoice QR-code, i’ll always get following error message, if I will spend some sats over any lightning wallet:

«Error: Failed to decode invoice, please try again» or «This dosen’t do be a lightning invoice»

<img width="1151" alt="Screenshot 2023-08-26 at 16 20 37" src="https://github.com/lnbits/lnbits-extensions/assets/87816768/f2a15e8a-7148-45dc-87ab-c48ea30c1ed3">

in the meantime i have compared the LNURLp QR code with a legend LNbits invoice. it is all the same except for one exception. with the legend invoice the wallet ID is a number, with my local LNbits wallet the ID consists of letters. as i understand it, this could be the problem that triggers the error message.

and if yes, how can I fix that?  

@arcbtc 

Rest of my config seems to be right and working. I used this manual:
https://raspibolt.org/guide/bonus/lightning/lnbits.html

**Comment by n-e-t-d-i-v-e-r** [comment]
delete what? the LNURLp-code and generate a new one? I tried this since many times, with always the same result.

also uninstalled and reinstalled the LNURLp extension, same error ...

but all the rest is working fine. strange ...

**Comment by dni** [comment]
![screenshot-1693135498](https://github.com/lnbits/lnurlp/assets/1743657/121c5d62-bbf2-4c63-99d7-f232b1537bdd)

the ID: 1231 < was the old IDs for lnurlp links created before 6 months ago
the ID: xfdsa < id created since then

**Comment by n-e-t-d-i-v-e-r** [comment]
OK, thanks for clarification. but why i’ll get an error-message, with this QR from my local server, when scanning with phoenix-wallet? maybe, because LNURLp is behind tor?
<img width="487" alt="Screenshot 2023-08-27 at 13 32 47" src="https://github.com/lnbits/lnurlp/assets/87816768/b58a6cc1-d466-47a7-8626-6821ef7071d2">

**Comment by n-e-t-d-i-v-e-r** [comment]
the issue was and is, that phoenix wallet can’t handle LNurl. tests with blueWallet were successful.
