### ISSUE TITLE
Capital Letters in LNaddress fail

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/lnurlp#18]
Though i get that the DB-entries need a harmonized format it should not be a requirement in the frontend. 
Can we reformat from capital to small letters on saving (if no such lnaddress is already stored) ?

<img width="571" alt="Bildschirmfoto 2023-08-27 um 15 12 18" src="https://github.com/lnbits/lnurlp/assets/63317640/715b2759-0452-4b9d-acdf-9cd5b55db7ad">

**Comment by bitkarrot** [comment]
If you read the Lightning address specification it is limited to the lower case letters here: 
https://github.com/lnurl/luds/blob/luds/16.md

If you mean you want an automated upper-to-lower conversion in the front end input form, feel free to make that a javascript PR hehe :)

**Comment by arbadacarbaYK** [comment]
> If you read the Lightning address specification it is limited to the lower case letters here: https://github.com/lnurl/luds/blob/luds/16.md
> 
> If you mean you want an automated upper-to-lower conversion in the front end input form, feel free to make that a javascript PR hehe :)

no, i mean when writing the link to the database ("on saving")
