### ISSUE TITLE
Duplicate LNURL Pay Link Identifiers Allowed via API

### ISSUE THREAD

**Issue by kenshortrede** [lnbits/lnurlp#32]
Dear LnBits Team,

I've encountered an issue where the API allows updating LNURL pay links with identifiers that are already in use. When creating a pay link, the system correctly identifies duplicates and prevents the operation. However, the same validation does not seem to be in place when interacting with the update endpoint.

This can lead to multiple LNURLs with the same identifier, which could cause confusion or errors in payment processing. Since the `GET /lnurlp/api/v1/links/` endpoint only returns links for a single account, there's no way to perform a comprehensive check for uniqueness from the client side.

Thank you for looking into this matter.

**Comment by prusnak** [comment]
Version of LNbits and version of the lnurlp extension?

**Comment by kenshortrede** [comment]
I think you were right. Just updated to 0.3.3 and it seems to work. There is something weird going on with the NOSTR zaps option, but I will update once I test it out more. 

Duplicate LNURL usernames now seem to work fine both on create and update

**Comment by prusnak** [comment]
Thanks!
Please open a new issue if you find another one.
