### ISSUE TITLE
Username already exists. Try a different one.

### ISSUE THREAD

**Issue by prusnak** [lnbits/lnurlp#38]
When I edit paylink and there is already a set username (I don't change it). On saving I see this error:

`
Exception: Username already exists. Try a different one.
`

The workaround is to unset it and then set it again in another edit.

**Comment by mrbpp** [comment]
I encountered the same issue and forgot to mention it. 

Thanks, I will try your method.

**Comment by dni** [comment]
fixed by https://github.com/lnbits/lnurlp/pull/45
