### ISSUE TITLE
[Feature Request] Allow longer lightning addresses

### ISSUE THREAD

**Issue by MichaelAntonFischer** [lnbits/lnurlp#39]
Increase the length of LNAdresses allowed. 15 is rather low and doesn't allow hooking up your email address to Lightning if you have a long name. I think 210 is a good limit.

**Comment by mrbpp** [comment]
In my opinion 128 is better than 210.

**Comment by dni** [comment]
i would like to adhere to the email standard `64` @prusnak @motorina0 what do you think?

**Comment by prusnak** [comment]
> i would like to adhere to the email standard `64` @prusnak @motorina0 what do you think?

Yes. 64 is fine 👍 (RFC 3696)

**Comment by motorina0** [comment]
> i would like to adhere to the email standard `64` @prusnak @motorina0 what do you think?

👍

**Comment by prusnak** [comment]
Limit bumped to 64 in https://github.com/lnbits/lnurlp/pull/41
