### ISSUE TITLE
[BUG] False error-msg after wrong but unsaved input

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/lnurlp#43]
Legend LNbits

Wrong input of text into "Success-URL", 
delete (not saved!) and fill text into right field "Success Message"
=> Error https missing, right credentials cannot be saved anylonger without exiting and full redo

https://github.com/lnbits/lnurlp/assets/63317640/69d55fd2-6da9-43cf-8e88-0b0ef629ace8

**Comment by dni** [comment]
thanks for the report, fixed in: https://github.com/lnbits/lnurlp/pull/44
