### ISSUE TITLE
Webhook broken (?) plus parameter documentation

### ISSUE THREAD

**Issue by dadofsambonzuki** [lnbits/lnurlp#6]
Hey,

We're trying to get the LNURLp webhook working with our Discord, but it doesn't seem to be firing. Other webhooks working fine.

Is there an bug with the latest version `0.2.1`?

Also, could someone update the README to explain how to use the webook headers and webhook custom data fields.

Cheers!

**Comment by dadofsambonzuki** [comment]
Doesn't look like anything is hooked-up in `success_action`.

https://github.com/lnbits/lnurlp/blob/4022faf778fffc8801bcab168413afefa51e5cf6/lnurl.py#LL91C55-L91C55

**Comment by dni** [comment]
the webhook is dispatched here, when invoice is paid. https://github.com/lnbits/lnurlp/blob/4022faf778fffc8801bcab168413afefa51e5cf6/tasks.py#L33

**Comment by talvasconcelos** [comment]
Webhook custom data, and headers are not passing from the UI to the DB!
