### ISSUE TITLE
Zap from strike/primal

### ISSUE THREAD

**Issue by bitkarrot** [lnbits/lnurlp#64]
See issue referenced here: 

https://github.com/nostrability/nostrability/issues/56

**Comment by derekross** [comment]
it looks like this may have been fixed in the 0.5.3 release, but that version is not available in the lnbits extension library yet. how can we get this pushed to prod so we can install it via lnbits?

**Comment by prusnak** [comment]
when this PR gets another 2 acks, then it will be updated in the extensions library: https://github.com/lnbits/lnbits-extensions/pull/414

**Comment by bitkarrot** [comment]
if you can't wait for the acks, v0.5.6 should be available when adding the manifest directly to the server admin panel, provided you have access to it. 

e.g. https://raw.githubusercontent.com/lnbits/lnurlp/main/manifest.json

**Comment by prusnak** [comment]
lnurlp 0.5.6 deployed:

https://github.com/lnbits/lnbits-extensions/pull/418
