### ISSUE TITLE
One can set duplicate LNaddress to already existing

### ISSUE THREAD

**Issue by prusnak** [lnbits/lnurlp#7]
When I am creating a new Pay Link with a LN address that is colliding with already existing one, I'll get this error:

`Username already exists. Try a different one.`

However, when I am editing an existing Pay Link and I change LN address to something that is already present in the system, no error is shown and the LN address alias is saved.

Luckily, this does not seem to overtake the existing LN address, but still, it would be nice if this was not allowed at all.

**Comment by Bashy** [comment]
I wrote #8 to address this issue.

**Comment by Bashy** [comment]
Fixed by #8 (merged yesterday), this issue can be closed
