### ISSUE TITLE
LNURLp broken - LNaddress not working

### ISSUE THREAD

**Issue by Satoshi-Samourai** [lnbits/lnurlp#75]
I am running LNBits on v0.12.12 with LNURLp extension v0.5.6.

The Lightning address seems to be broken. I can scan the lightning adress from LNBits PayLinks extension and pay to it but :

testuser@lnbits.btc-payserver.eu returns an "address not existing". Decoder confirms issue, too. 

Not sue if this is a LNBits v0.12.12 issue, as with earlier versions my LNaddresses worked just fine.

I have tried this: 

https://lnbits.btc-payserver.eu/lnurlp/api/v1/well-known/testuserwallet

returns propper json:

{
  "tag": "payRequest",
  "callback": "https://lnbits.btc-payserver.eu/lnurlp/api/v1/lnurl/cb/FGgzTb",
  "minSendable": 1000,
  "maxSendable": 100000,
  "metadata": "[[\"text/plain\", \"Payment to testuser\"], [\"text/identifier\", \"testuser@lnbits.btc-payserver.eu\"]]",
  "commentAllowed": 200,
  "allowsNostr": true,
  "nostrPubkey": "e1585e0db30c182c52c6fd18a2b1b0fdb4ee73ddfdee873d23aaf77977310e4d"
}

------------------------------------------------------------

https://lnbits.btc-payserver.eu/.well-known/lnurlp/testuserwallet

returns error:

{
  "status": "ERROR",
  "reason": "Address not found."
}
_________________________________________________________________

There seem to be more people having the same issue as discussed in LNBits Telegram Group.

Thanks for looking into this. It would be nice if it could get a quick fix.

Greets

**Comment by Satoshi-Samourai** [comment]
The conflict between lnaddress and lnurlp extension was the issue. 

Uninstalling lnaddress extension made lnurlp work. 

Thank you very much for your help in resolving the issue @warioishere @wario_is_here

**Comment by warioishere** [comment]
then lnaddress plugin overwrote the answer from the server when a GET request was made from a App paying to a lnadress

the server with both plugins installed answered the request with 

`/lnaddress/api/v1/well-known/<user>
`
the addresse registered with lnurlpay links extextions are registered under

`/lnurlp/api/v1/well-known/<user>`

With both exentions enabled the server served the link where the user registered with paylinks ist not availabe --> not found.

Maybe devs of lnaddress could fix this by using the same link?
