### ISSUE TITLE
Zapsupport version preventing startup if Nostrclient uninstalled

### ISSUE THREAD

**Issue by pardus79** [lnbits/lnurlp#9]
Trying to reinstall Nostrclient extension. Uninstalled in Lnbits. In "Manage Extensions" it would not give the option to then reinstall.

Restarted Lnbits and it gave an error saying Nostrclient not installed and that lnurlp should be checked to ensure the extension is following conventions. This prevented Lnbits from starting-up.

Had to delete lnurlp folder manually to get Lnbits to start.

**Comment by talvasconcelos** [comment]
@callebtc

**Comment by callebtc** [comment]
Hi @pardus79, are you sure you're not using a dev version of lnurlp on some previous commit?

The current extension on this branch does not import nostrclient anymore: https://github.com/lnbits/lnurlp/tree/zap_support

**Comment by pardus79** [comment]
Could have been a prior version. It was installed a few weeks back. I nuked my entire setup last week when I had the issue so I'm now running the current commit.
